### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-single-page-app#1]
**Routes**
- [ ] Browsing to the URL /#!/ displays a list of the available recipes
- [ ] Browsing to the URL /#!/edit/{id} displays the details for the specified recipe

**Recipes Screen**
- [ ] Displays the list of available recipes
- [ ] Selecting a category filters the list of recipes by that category
- [ ] Clicking on a recipe row’s “Edit” link displays the “Recipe Detail” screen for that recipe
- [ ] Clicking on a recipe row’s “Delete” link deletes that row’s recipe
- [ ] Clicking the “Add Recipe” button displays the “Recipe Detail” screen so that a recipe can be added
- [ ] (Extra) When deleting a recipe, the user is asked for confirmation before the item is deleted

**Recipe Detail Screen**
- [ ] Displays the detail for the specified recipe
- [ ] When adding or updating a recipe the following values are properly saved: Name, Description, Category, Prep Time, Cook Time
- [ ] One or more ingredients can be added
- [ ] One or more steps can be added
- [ ] When adding or updating an ingredient the following values are properly saved: Item, Condition, Quantity
- [ ] When adding or updating a step the “Description” value is properly saved

**Uses Immediately Invoked Function Expression**
- [ ] All JavaScript files use immediately invoked functions to keep variables and/or functions from leaking into the global namespace.
